-- ═══════════════════════════════════════════════════════════════════
-- Rawabit RAG — Migration 001: pgvector + ai_chunks table
-- ═══════════════════════════════════════════════════════════════════
-- Target:  Supabase PostgreSQL (pgvector enabled)
-- Model:   intfloat/multilingual-e5-small  →  384-dimensional vectors
-- Index:   HNSW with cosine distance operator
-- ═══════════════════════════════════════════════════════════════════

-- 1. Enable pgvector extension (Supabase hosts extensions in the
--    'extensions' schema by convention).
CREATE EXTENSION IF NOT EXISTS vector SCHEMA extensions;

-- 2. Create the ai_chunks table.
--    Each row holds one text chunk, its source reference, the 384-d
--    embedding vector, and an optional JSONB metadata bag.
CREATE TABLE IF NOT EXISTS public.ai_chunks (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ── Source reference ────────────────────────────────────────
    source_table    text        NOT NULL,       -- e.g. 'person', 'university'
    source_id       text        NOT NULL,       -- PK of the source row (text to handle UUIDs + bigints)

    -- ── Content ─────────────────────────────────────────────────
    chunk_text      text        NOT NULL,       -- the raw text chunk
    chunk_index     smallint    NOT NULL DEFAULT 0,  -- ordering within the source document

    -- ── Embedding ───────────────────────────────────────────────
    embedding       vector(384) NOT NULL,       -- multilingual-e5-small output

    -- ── Metadata ────────────────────────────────────────────────
    metadata        jsonb       DEFAULT '{}'::jsonb,

    -- ── Timestamps ──────────────────────────────────────────────
    created_at      timestamptz DEFAULT now()   NOT NULL
);

-- Composite uniqueness: one chunk per source document per index position.
CREATE UNIQUE INDEX IF NOT EXISTS uq_ai_chunks_source
    ON public.ai_chunks (source_table, source_id, chunk_index);

-- 3. HNSW index for fast approximate nearest-neighbour search.
--    Cosine distance operator class: vector_cosine_ops.
--    m=16, ef_construction=64 are balanced defaults for <100k rows.
CREATE INDEX IF NOT EXISTS idx_ai_chunks_embedding_hnsw
    ON public.ai_chunks
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- 4. B-tree indexes for filtering and source lookups.
CREATE INDEX IF NOT EXISTS idx_ai_chunks_source_table
    ON public.ai_chunks (source_table);
CREATE INDEX IF NOT EXISTS idx_ai_chunks_source_id
    ON public.ai_chunks (source_id);

-- 5. RPC function: match_chunks
--    Called from the application to perform similarity search.
--    Uses cosine distance (<=> operator); converts to similarity (1 - distance).
--    Filters results below the given threshold and returns top-N matches.
CREATE OR REPLACE FUNCTION public.match_chunks(
    query_embedding     vector(384),
    match_threshold     float       DEFAULT 0.72,
    match_count         int         DEFAULT 5,
    filter_source_table text        DEFAULT NULL
)
RETURNS TABLE (
    id              bigint,
    source_table    text,
    source_id       text,
    chunk_text      text,
    chunk_index     smallint,
    metadata        jsonb,
    similarity      float
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ac.id,
        ac.source_table,
        ac.source_id,
        ac.chunk_text,
        ac.chunk_index,
        ac.metadata,
        (1 - (ac.embedding <=> query_embedding))::float AS similarity
    FROM
        public.ai_chunks ac
    WHERE
        (1 - (ac.embedding <=> query_embedding)) > match_threshold
        AND (filter_source_table IS NULL OR ac.source_table = filter_source_table)
    ORDER BY
        ac.embedding <=> query_embedding ASC
    LIMIT
        match_count;
END;
$$;

-- 6. Grant execute on the RPC to the anon and authenticated roles
--    so Supabase client calls work out of the box.
GRANT EXECUTE ON FUNCTION public.match_chunks TO anon, authenticated;

-- 7. Enable RLS (default-deny) and allow anon SELECT.
ALTER TABLE public.ai_chunks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_ai_chunks"
    ON public.ai_chunks
    FOR SELECT
    TO anon
    USING (true);

CREATE POLICY "service_role_all_ai_chunks"
    ON public.ai_chunks
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

COMMENT ON TABLE  public.ai_chunks         IS 'RAG vector store: chunked text with 384-d embeddings from multilingual-e5-small';
COMMENT ON FUNCTION public.match_chunks    IS 'Cosine similarity search over ai_chunks; returns rows above threshold ordered by relevance';
